// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEKuNziG1rSZLQc9ElEgXc9g2WSYN6nWY',
    appId: '1:612983463124:web:8770d33bf79a1d4fbe6f41',
    messagingSenderId: '612983463124',
    projectId: 'mynotes-flutter-project-cb2fe',
    authDomain: 'mynotes-flutter-project-cb2fe.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-cb2fe.appspot.com',
    measurementId: 'G-V68RCDBRC9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDlFMNooa7qdGcWgCKNUnaFmOHDC8casQ',
    appId: '1:612983463124:ios:883f85d8cd8cdb43be6f41',
    messagingSenderId: '612983463124',
    projectId: 'mynotes-flutter-project-cb2fe',
    storageBucket: 'mynotes-flutter-project-cb2fe.appspot.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEKuNziG1rSZLQc9ElEgXc9g2WSYN6nWY',
    appId: '1:612983463124:web:11f4eafade64a7b0be6f41',
    messagingSenderId: '612983463124',
    projectId: 'mynotes-flutter-project-cb2fe',
    authDomain: 'mynotes-flutter-project-cb2fe.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-cb2fe.appspot.com',
    measurementId: 'G-ZB24WH342D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL09hb3_2yXXL3z0jZBtCp6jetnG73f3Y',
    appId: '1:51218108800:ios:f9a27cd813d33a14e87165',
    messagingSenderId: '51218108800',
    projectId: 'mynotes1-flutter',
    storageBucket: 'mynotes1-flutter.appspot.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ__byHaEgS2t22XLZU1alvjvP9H1TH_M',
    appId: '1:51218108800:android:b6a7cc26daf92634e87165',
    messagingSenderId: '51218108800',
    projectId: 'mynotes1-flutter',
    storageBucket: 'mynotes1-flutter.appspot.com',
  );

}